# WARNING - Generated by {fusen} from /dev/prssim.Rmd: do not edit by hand

test_that("risk_rel_high_prs works", {
  expect_type(risk_rel_high_prs(q = 0.1, d = 2), "double")
  expect_error(risk_rel_high_prs(q = 0.1, d = -1))
  expect_error(risk_rel_high_prs(q = -1, d = 0))
})
