# WARNING - Generated by {fusen} from /dev/prssim.Rmd: do not edit by hand

test_that("risk_rel_affected works", {
  expect_type(risk_rel_affected(q = 0.25, d = 1, r2 = 0.02, K = 0.05), "double")
  expect_error(risk_rel_affected(q = 0.25, d = 1, r2 = 0.02, K = -0.05))
  expect_error(risk_rel_affected(q = 10.25, d = 1, r2 = 0.02, K = 0.05))
})
