# WARNING - Generated by {fusen} from /dev/prssim.Rmd: do not edit by hand

test_that("risk_sib_affected works", {
  expect_type(risk_sib_affected(0.01, 0.05, 0.1), "double")
  expect_error(risk_sib_affected("a", "b", "c"))
})
