# WARNING - Generated by {fusen} from /dev/prssim.Rmd: do not edit by hand

test_that("risk_sib_high_prs works", {
  expect_type(risk_sib_high_prs(0.25), "double")
  expect_error(risk_sib_high_prs(2))
  expect_error(risk_sib_high_prs(q = "a"))
})
