# WARNING - Generated by {fusen} from /dev/prssim.Rmd: do not edit by hand

#' Estimate Prevalence of Disease Among First-Degree Relatives
#' 
#' This function enables the user to estimate the prevalence of disease among first-degree relatives of probands with elevated polygenic risk (within the top `q` of the PRS distribution), based on a disease with population prevalence `K`, and proportion of variability (r^2^) explained by the PRS `r`.
#' 
#' @param q (numeric; range = 0 to 1) Top quantile of risk used to define "elevated" risk in the proband. For example, if interested in the top 1% of risk, q = 0.01.
#' @param K (numeric; range = 0 to 1) Population prevalence of disease 
#' @param r (numeric; range = 0 to 1) Proportion of variability explained by the PRS (r^2^)
#'
#' @return (numeric) Prevalence of disease among relatives
#' 
#' @export


#' @examples
#' risk_sib_affected(0.01, 0.05, 0.1)
risk_sib_affected <- function(q,K,r) {
  checkmate::assert_number(q, lower = 0, upper = 1)
  checkmate::assert_number(K, lower = 0, upper = 1)
  checkmate::assert_number(r, lower = 0, upper = 1)
  
 zq <- qnorm(1-q)
 zK <- qnorm(1-K)
 integrand = function(t) {
 arg1 <- zq*sqrt(2)-t
 arg2 <- (zK-t*r/sqrt(2)) / (sqrt(1-r^2/2))
 return(dnorm(t)*pnorm(arg1,lower.tail=F)*pnorm(arg2,lower.tail=F) / q)
 }
 return(integrate(integrand,-Inf,Inf)$value)
}
