# WARNING - Generated by {fusen} from /dev/prssim.Rmd: do not edit by hand

#' Estimate Prevalence of Elevated PRS Among Relatives of d-degree
#'
#' This function enables the user to estimate the prevalence of elevated polygenic risk among `d`-degree relatives of probands with elevated polygenic risk (within the top `q` of the PRS distribution).
#'
#' @param q (numeric; range = 0 to 1) Top quantile of risk used to define "elevated" risk in the proband. For example, if interested in the top 1% of risk, q = 0.01.
#' @param d (integer) Degree of relationship to relatives
#'
#' @return (numeric) Prevalence of elevated polygenic risk (top `q` of the PRS distribution) among relatives of `d`-degree
#'
#' @export

#' @examples
#' risk_rel_high_prs(q = 0.1, d = 1)
risk_rel_high_prs <- function(q, d) {
  checkmate::assert_number(q, lower = 0, upper = 1)
  checkmate::assert_number(d, lower = 0)
  zq <- qnorm(1 - q)
  e <- 2^d
  integrand <- function(t) {
    return(dnorm(t) * pnorm((2^d * zq - t) / sqrt(2^(2 * d) - 1), lower.tail = F) / q)
  }
  return(integrate(integrand, zq, Inf)$value)
}
