# WARNING - Generated by {fusen} from /dev/prssim.Rmd: do not edit by hand

#' Estimate sibling risk
#'
#' @param q (numeric; range = 0 to 1) Top quantile of risk used to define "elevated" risk in the proband. For example, if interested in the top 1% of risk, q = 0.01.
#'
#' @return (numeric) Prevalence of elevated polygenic risk among first-degree relatives
#' @export
#'
#'
#' @examples
#' risk_sib_high_prs(q = .25)
risk_sib_high_prs <- function(q) {
  
  checkmate::assert_numeric(q, lower = 0, upper = 1)
  
  integrand <- function(t) {
    return(dnorm(t) * pnorm(qnorm(1 - q) * sqrt(2) - t, lower.tail = F)^2 / q)
  }
  return(integrate(integrand, -Inf, Inf)$value)
}

