# WARNING - Generated by {fusen} from /dev/prssim.Rmd: do not edit by hand

#' Estimate Prevalence of Disease Among d-Degree Relatives
#'
#' This function enables the user to estimate the prevalence of disease among `d`-degree relatives of probands with elevated polygenic risk (within the top `q` of the PRS distribution), based on a disease with population prevalence `K`, and proportion of variability (r^2^) explained by the PRS `r2`.
#'
#' @param q (numeric; range = 0 to 1) Top quantile of risk used to define "elevated" risk in the proband. For example, if interested in the top 1% of risk, q = 0.01.
#' @param K (numeric; range = 0 to 1) Population prevalence of disease
#' @param r2 (numeric; range = 0 to 1) Proportion of variability explained by the PRS (r^2^)
#' @param d (integer) Degree of relationship to relatives
#'
#' @return
#'
#' @export


#' @examples
#' risk_rel_affected(q = 0.25, d = 1, r2 = 0.02, K = 0.05)
risk_rel_affected <- function(q, K, r2, d) {
  checkmate::assert_number(q, lower = 0, upper = 1)
  checkmate::assert_number(K, lower = 0, upper = 1)
  checkmate::assert_number(r2, lower = 0, upper = 1)
  checkmate::assert_numeric(d, lower = 0)

  r <- sqrt(r2)
  zq <- qnorm(1 - q)
  zK <- qnorm(1 - K)
  integrand_inner <- function(tp, t) {
    arg1 <- (zK - r * sqrt(1 - 2^(-2 * d)) * tp) / sqrt(1 - r^2)
    arg2 <- tp - t / sqrt(2^(2 * d) - 1)
    return(pnorm(arg1, lower.tail = F) * dnorm(arg2))
  }
  integrand_outer <- function(ts) {
    y <- numeric(length(ts))
    for (i in seq_along(ts))
    {
      t <- ts[i]
      inner <- integrate(integrand_inner, -Inf, Inf, t)$value
      y[i] <- dnorm(t) * inner / q
    }
    return(y)
  }
  return(integrate(integrand_outer, zq, Inf)$value)
}
